name: deploy to aliyun oss
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.79.1'
          # extended: true

    - name: Build
      run: hugo --minify
      
 
    - name: upload files to aliyun OSS
      uses: fangbinwei/aliyun-oss-website-action@v1
      with:
          accessKeyId: ${{ secrets.OSS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_KEY_SECRET }}
          bucket: bobjiangcom1
          # e.g. "oss-cn-shanghai.aliyuncs.com"
          endpoint: oss-cn-beijing.aliyuncs.com
          folder: ./public/

